# Generated by Django 5.1.7 on 2025-04-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accommodation",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="campus",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
