# Generated by Django 5.1.7 on 2025-04-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Reservation",
            "0002_alter_accommodation_options_alter_campus_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="accommodation",
            table="Accommodation",
        ),
        migrations.AlterModelTable(
            name="campus",
            table="Campus",
        ),
        migrations.AlterModelTable(
            name="rating",
            table="Rating",
        ),
        migrations.AlterModelTable(
            name="reservation",
            table="Reservation",
        ),
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
