# Generated by Django 5.1.7 on 2025-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialist",
            fields=[
                ("specialist_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Specialist",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "Student",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
